### ISSUE TITLE
Use in own projects

### ISSUE THREAD

**Issue by AMDmi3** [AMDmi3/aesqlapius#12]
Dogfood by switching all own projects to this module. The list of missing features per-project:
- [ ] pypicache
  - [x] single value row type support
  - [x] reexport Namespace from __init__ for using in client type annotations
  - [ ] support adding `commit()` method to target root namespace (#15)
  - [ ] psycopg2 server-side cursor support (#8)
  - [x] parse complex argument and return type annotations properly (#16)
- [ ] repology-linkchecker
  - [x] aiopg support
- [ ] repology-updater
  - [ ] custom query postprocessor support (templates)
  - [ ] support for executemany with custom types
- [ ] repology-webapp
  - [ ] custom query postprocessor support (templates)
- [ ] repology-vulnupdater
